PUT http://localhost:5000/api/departments/bec0b5a5-0a57-437a-9bd5-cc07812fd4ca/25c58701-aa83-4ea5-a51c-ed27c5b082da
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZTg4ODY3YS00ZGMzLTRlYTgtYWZhNy1kN2ZjM2Q1MGY3NDEiLCJjaWQiOiJiZWMwYjVhNS0wYTU3LTQzN2EtOWJkNS1jYzA3ODEyZmQ0Y2EiLCJpYXQiOjE3NTUxNzk3MDIsImV4cCI6MTc1NTE4MDYwMn0.qhiSLWW6tfX52Dnwk9IYenwQ5mGYhZZGmtnR53e1NX4
Content-Type: application/json

{ "name": "Fin & Billing" }
