const { Router } = require('express');
const router = Router();
router.use('/products', require('./product.router'));
router.use('/price-lists', require('./priceList.extras.router'));
router.use('/channels', require('./channel.extras.router'));
router.use('/brands', require('./brand.router'));
router.use('/categories', require('./category.router'));
router.use('/uoms', require('./uom.router'));
router.use('/product-types', require('./productType.router'));
router.use('/attributes', require('./attribute.router'));
router.use('/attribute-options', require('./attributeOption.router'));
router.use('/product-attribute-values', require('./productAttributeValue.router'));
router.use('/product-variants', require('./productVariant.router'));
router.use('/variant-options', require('./variantOption.router'));
router.use('/product-attachments', require('./productAttachment.router'));
router.use('/product-localizations', require('./productLocalization.router'));
router.use('/product-external-refs', require('./productExternalRef.router'));
router.use('/product-suppliers', require('./productSupplier.router'));
router.use('/product-components', require('./productComponent.router'));
router.use('/product-relations', require('./productRelation.router'));
router.use('/packaging-units', require('./packagingUnit.router'));
router.use('/tags', require('./tag.router'));
router.use('/product-tags', require('./productTag.router'));
router.use('/collections', require('./collection.router'));
router.use('/product-collections', require('./productCollection.router'));
router.use('/product-categories', require('./productCategory.router'));
router.use('/price-list-items', require('./priceListItem.router'));
router.use('/channel-listings', require('./channelListing.router'));
router.use('/channel-category-maps', require('./channelCategoryMap.router'));
router.use('/channels', require('./channel.router'));
router.use('/price-lists', require('./priceList.router'));
router.use('/tax-categories', require('./taxCategory.router'));
router.use('/shipping-classes', require('./shippingClass.router'));
module.exports = router;