DELETE http://localhost:5000/api/counterparties/d7e70f19-33ac-40a7-87c6-297b70cf2d8e/5d39bf91-0b58-4dbc-b081-84f2fa710aa5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZmIxZjFmYS05Y2NiLTQzNGMtOThhMi04NTk0NDQ4MTUzODYiLCJjaWQiOiJkN2U3MGYxOS0zM2FjLTQwYTctODdjNi0yOTdiNzBjZjJkOGUiLCJpYXQiOjE3NTUxODQwMzQsImV4cCI6MTc1NTI0ODgzNH0.SwJaOw2JmbSWL_ySGsDvVVGmu-WR9zSdBhPpZjiB4Qk