// src/config/menu.js
import {
  Star,
  Home,
  Building2,
  Sprout,
  Users,
  LineChart,
  CheckSquare,
  Calendar,
  MessagesSquare,
  FileText,
  Package,
  ClipboardList,
  Tag,
  Ticket,
  Truck,
  ShoppingBag,
  Wrench,
  Warehouse,
  File,
  ArrowRightLeft,
  BarChart3,
  LayoutDashboard,
  MapPin,
  BookMarked,
  Boxes,
  Barcode,
  PackageOpen,
} from "lucide-react";

export const MENU = [
  { key: "bookmarks", icon: Star, labelKey: "menu.bookmarks", type: "section" },

  // "Главная" → сразу в контрагентов
  { key: "pulpit", icon: Home, labelKey: "menu.pulpit", route: "/main/pulpit", type: "item" },

  { key: "crm", icon: Users, labelKey: "menu.crm", type: "section" },
  { key: "counterparties", icon: Building2, labelKey: "menu.counterparties", route: "/main/counterparties", type: "item" },
  { key: "leads", icon: Sprout, labelKey: "menu.leads", route: "/main/leads", type: "item", filterFlyout: true },
  { key: "clients", icon: Users, labelKey: "menu.clients", route: "/main/clients", type: "item", filterFlyout: true },
  { key: "deals", icon: LineChart, labelKey: "menu.deals", route: "/main/deals", type: "item" },
  { key: "tasks", icon: CheckSquare, labelKey: "menu.tasks", route: "/main/tasks", type: "item" },
  { key: "notes", icon: ClipboardList, labelKey: "menu.notes", route: "/main/notes", type: "item" },
  { key: "contacts", icon: Users, labelKey: "menu.contacts", route: "/main/contacts", type: "item" },
  { key: "calendar", icon: Calendar, labelKey: "menu.calendar", route: "/main/calendar", type: "item" },
  { key: "chat", icon: MessagesSquare, labelKey: "menu.chat", route: "/main/chat", type: "item" },

  { key: "oms", icon: FileText, labelKey: "menu.oms", type: "section" },
  { key: "invoices", icon: FileText, labelKey: "menu.invoices", route: "/main/oms/invoices", type: "item" },
  { key: "receipts", icon: FileText, labelKey: "menu.receipts", route: "/main/oms/receipts", type: "item" },
  { key: "orders", icon: ClipboardList, labelKey: "menu.orders", route: "/main/oms/orders", type: "item" },
  { key: "offers", icon: FileText, labelKey: "menu.offers", route: "/main/oms/offers", type: "item" },
  { key: "documents", icon: FileText, labelKey: "menu.documents", route: "/main/documents", type: "item" },
  { key: "promotions", icon: Tag, labelKey: "menu.promotions", route: "/main/oms/promotions", type: "item" },
  { key: "coupons", icon: Ticket, labelKey: "menu.coupons", route: "/main/oms/coupons", type: "item" },
  { key: "shipments", icon: Truck, labelKey: "menu.shipments", route: "/main/oms/shipments", type: "item" },

  { key: "pim", icon: ShoppingBag, labelKey: "menu.pim", type: "section" },
  { key: "products", icon: Package, labelKey: "menu.products", route: "/main/products", type: "item", filterFlyout: true },
  { key: "services", icon: Wrench, labelKey: "menu.services", route: "/main/pim/services", type: "item" },

  { key: "wms", icon: Warehouse, labelKey: "menu.wms", type: "section" },
  { key: "wmsOverview", icon: LayoutDashboard, labelKey: "menu.wmsOverview", route: "/main/wms", type: "item" },
  { key: "wmsReceipts", icon: File, labelKey: "menu.wmsReceipts", route: "/main/wms/receipts", type: "item" },
  { key: "transfers", icon: ArrowRightLeft, labelKey: "menu.transfers", route: "/main/wms/transfers", type: "item" },
  { key: "wmsShipments", icon: Truck, labelKey: "menu.wmsShipments", route: "/main/wms/shipments", type: "item" },
  { key: "wmsPicks", icon: ClipboardList, labelKey: "menu.wmsPicks", route: "/main/wms/picks", type: "item" },
  { key: "wmsNewShipment", icon: Truck, labelKey: "menu.wmsNewShipment", route: "/main/wms/shipments/new", type: "item" },
  { key: "wmsAdjustments", icon: File, labelKey: "menu.wmsAdjustments", route: "/main/wms/adjustments", type: "item" },
  { key: "wmsCycleCounts", icon: ClipboardList, labelKey: "menu.wmsCycleCounts", route: "/main/wms/cycle-counts", type: "item" },
  { key: "stockBalances", icon: Package, labelKey: "menu.stockBalances", route: "/main/wms/stock-balances", type: "item" },
  { key: "wmsStockMoves", icon: ArrowRightLeft, labelKey: "menu.wmsStockMoves", route: "/main/wms/stock-moves", type: "item" },
  { key: "wmsWarehouses", icon: Warehouse, labelKey: "menu.wmsWarehouses", route: "/main/wms/warehouses", type: "item" },
  { key: "wmsLocations", icon: MapPin, labelKey: "menu.wmsLocations", route: "/main/wms/locations", type: "item" },
  { key: "wmsReservations", icon: BookMarked, labelKey: "menu.wmsReservations", route: "/main/wms/reservations", type: "item" },
  { key: "wmsLots", icon: Boxes, labelKey: "menu.wmsLots", route: "/main/wms/lots", type: "item" },
  { key: "wmsSerials", icon: Barcode, labelKey: "menu.wmsSerials", route: "/main/wms/serials", type: "item" },
  { key: "wmsParcels", icon: PackageOpen, labelKey: "menu.wmsParcels", route: "/main/wms/parcels", type: "item" },
  // Workspace Views Phase 2: pinned views render under this item via
  // <WorkspaceViewsSidebarSection module="wms.documents" />. The per-type list pages
  // (receipts/transfers/shipments/adjustments/cycle-counts) and reports are still
  // reachable by URL — they no longer take a sidebar slot each.
  {
    key: "wmsDocuments",
    icon: FileText,
    labelKey: "menu.wmsDocuments",
    route: "/main/wms/documents",
    type: "item",
    workspaceViewsModule: "wms.documents",
  },
  { key: "wmsReports", icon: BarChart3, labelKey: "menu.wmsReports", route: "/main/wms/reports/stock-valuation", type: "item" },

  { key: "users", icon: Users, labelKey: "menu.users", route: "/main/company-users", type: "item" },
];
