GET http://localhost:5000/api/tasks/07ab610c-9704-4d38-891e-4d3f8cad7a9d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZGJjM2EyMy00YjNiLTQ2NGMtYjY5MC0zYmNjYTQ4Mjc2MmEiLCJjaWQiOiI1MWZhYWZjYy1mOTgyLTRiNGQtYWJjYi1hZmMxODczMzY1MjgiLCJpYXQiOjE3NTU1MjE2MTQsImV4cCI6MTc1NTU4NjQxNH0.RW0isgEark5H4lLCas8PZu9qRmlZUGcEhjsjFZ6fNJo